feat(falco-talon): Configure Talon pod to not rollout on configmap changes, allow user to input rules.yaml directly, configure Talon to rollout on secret change, bump appVersion v0.2.0
Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

feat: trigger rollout based on secret change

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

feat: remove rules_override.yaml file, add field so users can specify custom rules directly via values

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore: bump chart version, update CHANGELOG.md and make docs

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

feat: allow users to specify custom service accounts for deployment

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore: modify changelog.md

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore(deps): Bump lycheeverse/lychee-action from 2.0.2 to 2.1.0

Bumps [lycheeverse/lychee-action](https://github.com/lycheeverse/lychee-action) from 2.0.2 to 2.1.0.
- [Release notes](https://github.com/lycheeverse/lychee-action/releases)
- [Commits](https://github.com/lycheeverse/lychee-action/compare/7cd0af4c74a61395d455af97419279d86aafaede...f81112d0d2814ded911bd23e3beaa9dda9093915)

---
updated-dependencies:
- dependency-name: lycheeverse/lychee-action
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

feat: remove helm-generated labels and timestamp so that pod isn't recycled with a new update

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

feat: trigger rollout based on secret change

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

feat: remove rules_override.yaml file, add field so users can specify custom rules directly via values

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore: bump chart version, update CHANGELOG.md and make docs

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

feat: allow users to specify custom service accounts for deployment

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore: modify changelog.md

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore(deps): Bump lycheeverse/lychee-action from 2.0.2 to 2.1.0

Bumps [lycheeverse/lychee-action](https://github.com/lycheeverse/lychee-action) from 2.0.2 to 2.1.0.
- [Release notes](https://github.com/lycheeverse/lychee-action/releases)
- [Commits](https://github.com/lycheeverse/lychee-action/compare/7cd0af4c74a61395d455af97419279d86aafaede...f81112d0d2814ded911bd23e3beaa9dda9093915)

---
updated-dependencies:
- dependency-name: lycheeverse/lychee-action
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

change the key for the rulesfiles range

Signed-off-by: Thomas Labarussias <issif+github@gadz.org>

chore(falco/k8smeta): bump plugin version

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco/test): update unit tests to reflect changes in k8smeta tag

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco/k8smeta): bump chart version

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

fix(falco/dashboard): make pod variable independent of triggered rules

CPU and memory are now visible for each pod, even when no rules have been triggered for
that falco instance.

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco): bump chart version

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco): apply suggestions

Co-authored-by: Thomas Labarussias <issif+github@gadz.org>
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

fix(falco/readme): use rules_files instead of deprecated rules_file in config snippet

Using rules_file causes collision with rules_files and falco does not start

```
Tue Nov 12 14:23:17 2024: Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
Error: Error reading config file (/etc/falco/falco.yaml): both 'rules_files' and 'rules_file' keys set
```

Signed-off-by: Robin Landström <robinlandstrom@users.noreply.github.com>

chore(falco): bump chart version

Signed-off-by: Robin Landström <robinlandstrom@users.noreply.github.com>

update(falco): bump falco version to 0.39.2 and falcoctl to 0.10.1

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore: bump chart version

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore: update docs

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>

chore(deps): Bump lycheeverse/lychee-action from 2.0.2 to 2.1.0

Bumps [lycheeverse/lychee-action](https://github.com/lycheeverse/lychee-action) from 2.0.2 to 2.1.0.
- [Release notes](https://github.com/lycheeverse/lychee-action/releases)
- [Commits](https://github.com/lycheeverse/lychee-action/compare/7cd0af4c74a61395d455af97419279d86aafaede...f81112d0d2814ded911bd23e3beaa9dda9093915)

---
updated-dependencies:
- dependency-name: lycheeverse/lychee-action
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

change the key for the rulesfiles range

Signed-off-by: Thomas Labarussias <issif+github@gadz.org>

chore(falco/k8smeta): bump plugin version

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco/test): update unit tests to reflect changes in k8smeta tag

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco/k8smeta): bump chart version

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

fix(falco/dashboard): make pod variable independent of triggered rules

CPU and memory are now visible for each pod, even when no rules have been triggered for
that falco instance.

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco): bump chart version

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore(falco): apply suggestions

Co-authored-by: Thomas Labarussias <issif+github@gadz.org>
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

fix(falco/readme): use rules_files instead of deprecated rules_file in config snippet

Using rules_file causes collision with rules_files and falco does not start

```
Tue Nov 12 14:23:17 2024: Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
Error: Error reading config file (/etc/falco/falco.yaml): both 'rules_files' and 'rules_file' keys set
```

Signed-off-by: Robin Landström <robinlandstrom@users.noreply.github.com>

chore(falco): bump chart version

Signed-off-by: Robin Landström <robinlandstrom@users.noreply.github.com>

update(falco): bump falco version to 0.39.2 and falcoctl to 0.10.1

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

chore: bump appVersion to match talon version

Signed-off-by: Igor Eulalio <igor.eulalio@sysdig.com>